services:
  - type: web
    name: url-shortener
    env: node
    plan: free       
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: your_mongodb_atlas_uri
